version: "3.2"
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    # volumes:
    #  - './data:/data'
    #  - './conf/:/conf/'
    ports:
      - 7474:7474
      - 7687:7687
    restart: on-failure
    command: neo4j