version: '3'

services:
  postgres:
    image: postgres:12
    container_name: postgres_container
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      - PGHOST=localhost
      - PGDATABASE=postgres
      - PGUSER=postgres
      - POSTGRES_PASSWORD=0Canpass!!!
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: 'bitnami/redis:7.0'
    restart: always
    environment:
      - REDIS_PASSWORD=0Canpass!!!
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
       - internal
  
  asynqmon:
    image: hibiken/asynqmon:latest
    ports:
      - 8080:8080
    entrypoint: ["./asynqmon", "--redis-addr=redis:6379", "--redis-password=0Canpass!!!"]
    depends_on:
      - redis
    networks:
      - internal

  minio:
    image: "quay.io/minio/minio"
    command: server --console-address ":9001" /data
    restart: always
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: 0Canpass!!!
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - "minio_data:/data"

volumes:
  postgres:
  redis_data:
    driver: local
  minio_data:

networks:
  internal: