version: '3.7'
services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=product
    volumes:
      - ./configs:/etc/mongo
      - ./data:/data/db
    ports:
      - 27017:27017