version: '3'
services:
  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=huylq
      - MONGO_INITDB_ROOT_PASSWORD=huylq
      - MONGO_INITDB_DATABASE=product
    volumes:
      - ./configs:/etc/mongo
      - ./data:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=huylq
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=huylq
      - ME_CONFIG_BASICAUTH_USERNAME=huylq
      - ME_CONFIG_BASICAUTH_PASSWORD=huylq
    depends_on:
      - db
    ports:
      - "8888:8081"