version: '2'

services:
  postgres:
    image: postgres:12
    container_name: postgres_container
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      - PGHOST=localhost
      - PGDATABASE=postgres
      - PGUSER=postgres
      - POSTGRES_PASSWORD=password@123
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      - REDIS_PASSWORD=password@123
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  minio:
    image: "quay.io/minio/minio"
    command: server --console-address ":9001" /data
    restart: always
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: password@123
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - "minio_data:/data"

volumes:
  postgres:
  redis_data:
  minio_data:
