version: '2'

services:
  db-postgres:
    image: postgres:11
    container_name: postgres_container
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      - PGHOST=localhost
      - PGDATABASE=postgres
      - PGUSER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - my-db-postgres:/var/lib/postgresql/data

volumes:
  my-db-postgres: